### ISSUE TITLE
BAHAS OPOK / VMESS

### ISSUE THREAD

**Issue by sonzaiekkusu** [Manssizz/scriptvps#5]
pas beres gabisa masuk vps bang _-
udah ditunggu beberapa menit juga g bsa 
itu sshd_confignya udah bener belum??

**Comment by Sonzai-X** [comment]
![Screenshot_2023-02-05-15-58-37-732_com gatcha ang](https://user-images.githubusercontent.com/124268173/216810344-8f976b9f-5f39-4920-9753-bc5d5c09bc48.jpg)
Opoknya gak support

**Comment by sonzaiekkusu** [comment]
> ![Screenshot_2023-02-05-15-58-37-732_com gatcha ang](https://user-images.githubusercontent.com/124268173/216810344-8f976b9f-5f39-4920-9753-bc5d5c09bc48.jpg) Opoknya gak support

Iya emang opoknya gabsa padahal udah pake core xray punya dharak36 tp entah kenapa gabsa opoknya

**Comment by Manssizz** [comment]
coba install ulang. sebelumnya ada typo di link binary xray. 
untuk opok bisa pakai vmess.

**Comment by sonzaiekkusu** [comment]
> coba install ulang. sebelumnya ada typo di link binary xray. untuk opok bisa pakai vmess.

Oke siap

**Comment by XstepAhead** [comment]
> coba install ulang. sebelumnya ada typo di link binary xray. untuk opok bisa pakai vmess.

Btw udh d tes sma bang mamssizz nya opok??

**Comment by sonzaiekkusu** [comment]
> coba install ulang. sebelumnya ada typo di link binary xray. untuk opok bisa pakai vmess.

![Screenshot_2023-02-05-19-01-30-224_com gatcha ang](https://user-images.githubusercontent.com/61716582/216817489-1ffb23a1-5edc-45f7-b991-f1b72ff5fc87.jpg)
Tetep bang ga konek udah pake semua port juga sama aja ga ada yang konek kalo pake ilmupedia bisa tapi kalo opok gamau bisa

**Comment by Manssizz** [comment]
```
- name: test
  server: <domain>
  port: 80
  type: vmess
  uuid:<UUID>
  alterId: 0
  cipher: auto
  tls: false
  skip-cert-verify: true
  servername: cdn.instagram.com
  network: ws
  ws-opts:
    path: http://tsel.me/worryfree
    headers:
      Host: tsel.me
  udp: true
  ```
